name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  tag-commit:
    
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Bump version and push tag
        if: github.event_name != 'pull_request'
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          INITIAL_VERSION: 1.0.0
    
  image-build:
    runs-on: ubuntu-latest
    needs: tag-commit
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/redhat-actions/podman-login
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REPO_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Print tag 
        run: echo ${{ needs.tag-commit.outputs.new_tag }}
        
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ needs.tag-commit.outputs.new_tag }}
            type=semver,pattern={{major}}.{{minor}}


      - name: Build image with buildah
        id: build
        uses: redhat-actions/buildah-build@v2
        with: 
          context: ./
          oci: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          containerfiles: ./Dockerfile
    # Input "image" and "registry" is ignored when using full name tags
      - name: Push To ghcr
        if: github.event_name != 'pull_request'
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          #image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          #registry: ${{ env.REGISTRY }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push.outputs.registry-paths }}"
